aliases = [
	"Int8Array",
	"Uint8Array",
	"Uint8ClampedArray",
	"Int16Array",
	"Uint16Array",
	"Int32Array",
	"Uint32Array",
	"Float32Array",
	"Float64Array",
	"DataView"
]
license = "MIT"
repo = "https://github.com/inexorabletash/polyfill"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray"

[browsers]
android = "<4"
bb = "*"
chrome = "<7"
edge_mob = "*"
firefox = "<4"
ie = "<10"
ie_mob = "*"
ios_saf = "<4.2"
op_mini = "*"
opera = "<12"
safari = "<5.1"

[install]
module = "js-polyfills"
paths = [ "typedarray.js" ]
