#### Aliases
# An alias is another name for the polyfill that can be used when requesting a bundle.
# For example, the alias `es5` is used to replicate an ECMAScript 5 environment.
aliases = []

#### Dependencies
# List any web platform features that you use in your polyfill.
# For example:
# dependencies = [
#    "Object.defineProperty"
# ]
dependencies = []
spec = "https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element"
docs = "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details"

#### License
# The license this code has been given. All code authored within the polyfill-library itself is MIT.
# Third-party code can use any license which is listed on https://opensource.org/licenses
license = ""

[browsers]
android = "<4"
bb = "*"
chrome = "<12"
edge = "<79"
edge_mob = "<79"
firefox = "<49"
ios_chr = "*"
ios_saf = "<6"
ie = "*"
ie_mob = "*"
opera = "<15"
op_mini = "*"
safari = "<6"
firefox_mob = "<49"
samsung_mob = "<4"
